[package]
name = "smol_str"
version = "0.1.18"
description = "small-string optimized string type with O(1) clone"
license = "MIT OR Apache-2.0"
repository = "https://github.com/matklad/smol_str"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", optional = true, default_features = false }
arbitrary = { version = "1", optional = true }

[dev-dependencies]
proptest = "0.10"
serde_json = "1"
serde =  { version = "1", features = [ "derive" ] }

[features]
default = ["std"]
nosync = []
std = ["serde/std"]
